import 'festival_entry.dart';

/// Representative celebrations with explicitly named communities and calendars.
/// Descriptions are original editorial summaries of the named references.
class EthnicFestivalEntry extends FestivalEntry {
  const EthnicFestivalEntry({
    required this.community,
    required this.date,
    required super.name,
    required super.introduction,
    required super.history,
    required super.customs,
    required super.meaning,
    required super.note,
    required super.sourceTitle,
  });

  final String community;
  final String date;
}

const ethnicFestivalEntries = <EthnicFestivalEntry>[
  EthnicFestivalEntry(
    name: '藏历新年',
    community: '藏族等 · 西藏及其他藏区',
    date: '藏历正月初一',
    introduction: '藏历新年是藏族及藏区各族群众重要的年节。',
    history: '以藏历岁首为中心，年前准备、除旧与新年拜贺组成完整节期。',
    customs: '准备切玛、卡赛等年节物品，家人团聚，向长辈献哈达、互道祝福。',
    meaning: '辞旧迎新，祝愿丰收、平安，并维系亲友和社区关系。',
    note: '藏历和农历算法不同，藏历正月初一不总与春节同日；各藏区年俗也有差异。',
    sourceTitle: '山南市文化和旅游局：藏历新年习俗简介',
  ),
  EthnicFestivalEntry(
    name: '壮族三月三',
    community: '壮族 · 广西等地',
    date: '农历三月初三',
    introduction: '以歌圩、祭祖等活动闻名的壮族春季节庆。',
    history: '祭祖祈福、以歌交往等多层传统逐渐形成今天的节庆形态。',
    customs: '对歌、抛绣球、做五色糯米饭；部分地区有抢花炮等活动。',
    meaning: '联结社区、传承歌谣，也寄托春耕丰收与美好情感的愿望。',
    note: '“三月三”也是其他民族的节日，不能将各民族的内容合并为一套习俗。',
    sourceTitle: '中国非物质文化遗产网：多民族传统节日“三月三”',
  ),
  EthnicFestivalEntry(
    name: '畲族三月三',
    community: '畲族 · 浙江景宁等地',
    date: '农历三月初三',
    introduction: '畲族的春日节庆，也称乌饭节。',
    history: '景宁等畲族聚居地长期传承三月三节俗，兼具祭祖与春耕时序。',
    customs: '制作乌饭、走亲访友、对歌，并举行祭祖祈福活动。',
    meaning: '借饮食与歌会联结亲友，表达对祖先和丰年的敬意。',
    note: '乌饭制作、歌会形式因村寨而异；不等同于壮族三月三。',
    sourceTitle: '中国非物质文化遗产网：三月三，多民族共享的节日',
  ),
  EthnicFestivalEntry(
    name: '黎族三月三',
    community: '黎族 · 海南',
    date: '农历三月初三',
    introduction: '海南黎族纪念祖先、以歌舞表达情感的春日节庆。',
    history: '在黎族社区传承，并在现代成为展示当地文化的重要节日。',
    customs: '祭祖、对歌、民族歌舞和传统体育竞技。',
    meaning: '寄托对祖先的追念、对爱情与新生活的向往。',
    note: '海南不同地区活动各有重点，也有苗族等群众共同参与。',
    sourceTitle: '中国非物质文化遗产网：黎族三月三节',
  ),
  EthnicFestivalEntry(
    name: '苗族姊妹节',
    community: '苗族 · 贵州台江老屯、施洞一带',
    date: '农历三月十五至十七（当地）',
    introduction: '台江部分苗族社区以姊妹饭和青年交往为特色的节日。',
    history: '作为地方苗族节俗长期传承，既有青年交往，也有亲友与社区聚会。',
    customs: '制作彩色姊妹饭、走亲访友、盛装歌舞。',
    meaning: '增进社区联系，展示服饰、饮食与歌舞传统。',
    note: '这里采用台江老屯、施洞一带的日期和习俗，并非全部苗族地区统一节期。',
    sourceTitle: '中国非物质文化遗产网：苗族姊妹节',
  ),
  EthnicFestivalEntry(
    name: '泼水节',
    community: '傣族 · 云南等地',
    date: '傣历新年，公历通常在4月中旬',
    introduction: '傣族新年节庆，水象征祝福与洁净。',
    history: '与傣历岁首及南传佛教文化相关，节日内涵经长期交流而形成。',
    customs: '浴佛、相互泼水祝福；部分地区举行龙舟、歌舞等活动。',
    meaning: '辞旧迎新、彼此祝福，展示社区凝聚力。',
    note: '每年的具体公历日期、节期和仪式应以当地公布为准。',
    sourceTitle: '中国非物质文化遗产网：傣族泼水节',
  ),
  EthnicFestivalEntry(
    name: '那达慕',
    community: '蒙古族 · 内蒙古等地',
    date: '多在夏秋牧草丰茂时，日期不固定',
    introduction: '蒙古族传统群众性盛会，名称含“娱乐、游戏”之意。',
    history: '与草原集会、竞技和庆贺活动相连，形成多地传承的盛会。',
    customs: '搏克、赛马、射箭是代表性项目，现代活动还包括歌舞和物资交流。',
    meaning: '展现草原体育、技艺与共同生活。',
    note: '各地那达慕并非同一天，项目内容和举办规模也各异。',
    sourceTitle: '中国非物质文化遗产网：那达慕',
  ),
  EthnicFestivalEntry(
    name: '彝族火把节',
    community: '彝族 · 云南、四川、贵州等地',
    date: '多在农历六月廿四前后',
    introduction: '以点燃火把和集体歌舞为鲜明标志的彝族节日。',
    history: '与农事、火的象征及地方传说相连，起源有多种解释。',
    customs: '扎火把、歌舞、赛马、摔跤或赶集。',
    meaning: '祈愿庄稼生长、家园平安，并加强社区往来。',
    note: '白族等民族也有火把节，日期与仪式不能一概等同。',
    sourceTitle: '中国非物质文化遗产网：火把节（彝族火把节）',
  ),
  EthnicFestivalEntry(
    name: '雪顿节',
    community: '藏族 · 拉萨等地',
    date: '藏历六月末至七月初（地方节期）',
    introduction: '以藏戏、展佛和群众游园为代表内容的藏族节庆。',
    history: '“雪顿”原意与酸奶宴有关，后来融入藏戏演出及拉萨的公共游园活动。',
    customs: '观看藏戏、游园；一些活动包含展佛、马术和赛牦牛。',
    meaning: '传承藏戏等艺术，促进社区相聚。',
    note: '具体举办日期与活动安排依当地当年公告，不按公历固定。',
    sourceTitle: '中国非物质文化遗产网：雪顿节',
  ),
  EthnicFestivalEntry(
    name: '水族端节',
    community: '水族 · 贵州三都等地',
    date: '水历岁末岁首，约对应农历八至十月',
    introduction: '水族重要的辞旧迎新、庆祝谷熟的节日。',
    history: '依据水书、水历和地方传统择期，各地区按批次过节。',
    customs: '祭祖、亲友相聚，并举行地方性的节庆活动。',
    meaning: '庆贺收获、迎接新年并维系族群记忆。',
    note: '不是某一个固定农历日，不同村寨的节期可能相隔数周。',
    sourceTitle: '中国非物质文化遗产网：水族端节',
  ),
  EthnicFestivalEntry(
    name: '苗年',
    community: '苗族 · 贵州清水江、都柳江流域等地',
    date: '秋收后依苗历及当地商议择期',
    introduction: '部分苗族社区在秋收后举行的新年庆典。',
    history: '苗历岁首与当地农事相连，各寨可按顺序分别过年。',
    customs: '团年饭、打糯米粑、祭祖、跳芦笙舞、走村串寨。',
    meaning: '庆祝一年收成，传承祖先记忆与社区关系。',
    note: '苗族分布广泛，苗年并非所有苗族社区在同一天举行。',
    sourceTitle: '中国非物质文化遗产网：苗年',
  ),
  EthnicFestivalEntry(
    name: '羌年',
    community: '羌族 · 四川阿坝、北川等地',
    date: '通常农历十月初一',
    introduction: '羌族辞旧迎新、感恩收获的传统年节。',
    history: '围绕祭山、集体欢庆和家祭，维系与祖先及乡土的联系。',
    customs: '释比主持祈福，跳羊皮鼓舞；村寨歌舞、家人共宴。',
    meaning: '感谢自然与收成，祈愿人畜平安、社区和睦。',
    note: '庆祝可延续数日，各寨安排可能不同。',
    sourceTitle: '中国非物质文化遗产网：羌年',
  ),
  EthnicFestivalEntry(
    name: '盘王节',
    community: '瑶族 · 广西、湖南、广东等地',
    date: '农历十月十六（共同节期）',
    introduction: '瑶族纪念盘王的节庆，祖先记忆是重要主题。',
    history: '各地原有不同祭祀传统，20世纪80年代协商形成共同节期。',
    customs: '祭祀盘王、唱盘王歌、跳长鼓舞；地方还盘王愿仪式各有差异。',
    meaning: '追念祖先、凝聚族群并传承歌舞与历史叙事。',
    note: '不能用某地的仪式代表所有瑶族支系。',
    sourceTitle: '中国非物质文化遗产网：瑶族盘王节',
  ),
  EthnicFestivalEntry(
    name: '侗年',
    community: '侗族 · 贵州黔东南等地',
    date: '多在农历十一月前后，村寨轮流举行',
    introduction: '部分侗族村寨的传统年节。',
    history: '与秋收后的休整和亲友往来相连，不同寨子按传统依次庆贺。',
    customs: '祭祖、吃年饭、走寨拜年，伴随歌舞和交往活动。',
    meaning: '庆祝收获、维系村寨关系和地方文化记忆。',
    note: '并无所有侗寨共用的单一日期。',
    sourceTitle: '中国非物质文化遗产网：侗年',
  ),
  EthnicFestivalEntry(
    name: '彝族年',
    community: '彝族 · 四川凉山等地',
    date: '秋收后择吉日，多在公历11月前后',
    introduction: '凉山等地彝族的传统新年，彝语称“库史”。',
    history: '以秋收之后的择日年节为核心，融合祭祖、饮食和游艺。',
    customs: '年前备食与清扫，年节中祭祖、团聚、访亲和娱乐。',
    meaning: '庆祝收成，祈愿家人安康。',
    note: '日期由当地择定，不应固定写为每年11月20日。',
    sourceTitle: '中国非物质文化遗产网：彝族年',
  ),
  EthnicFestivalEntry(
    name: '阔时节',
    community: '傈僳族 · 云南怒江等地',
    date: '岁末年初，具体节期依地方安排',
    introduction: '傈僳族传统新年，“阔时”意为新年。',
    history: '在怒江流域等傈僳族社区长期传承，后来也成为当地各族共享的节庆。',
    customs: '舂粑粑、祭祖祈福；之后走亲访友、对歌与射弩等。',
    meaning: '辞旧迎新，维系社区互助和民族记忆。',
    note: '各地日期、节期长短和活动内容可能不同。',
    sourceTitle: '中国非物质文化遗产网：阔时节',
  ),
  EthnicFestivalEntry(
    name: '开斋节',
    community: '多个民族中的穆斯林群体',
    date: '伊斯兰教历十月初一',
    introduction: '斋月结束后庆祝的伊斯兰教节日。',
    history: '随伊斯兰教传播，成为中国回族、维吾尔族等多个民族中穆斯林的节日。',
    customs: '礼拜、走亲访友、分享节日食物。',
    meaning: '表达感恩、友爱与亲友团聚。',
    note: '按伊斯兰教历确定，公历日期逐年变化；信仰不等同于民族身份。',
    sourceTitle: '北京市委统战部：回族',
  ),
  EthnicFestivalEntry(
    name: '古尔邦节',
    community: '多个民族中的穆斯林群体',
    date: '伊斯兰教历十二月初十',
    introduction: '又称宰牲节，是穆斯林重要的宗教节日。',
    history: '与伊斯兰教朝觐及易卜拉欣故事相关，在中国多民族穆斯林社区传承。',
    customs: '礼拜、亲友团聚和分享食物；具体仪式以各地宗教实践为准。',
    meaning: '强调感恩、分享与互助。',
    note: '依伊斯兰教历推算，公历日期每年改变；并非某一民族独有。',
    sourceTitle: '北京市委统战部：回族',
  ),
];
